export const GET_GAMES = 'GET_GAMES';
export const GET_GAMES_BY_NAME = 'GET_GAMES_BY_NAME';
export const RESET_GAMES_BY_NAME = 'RESET_GAMES_BY_NAME';
export const FILTER_GAMES_BY_GENRE = 'FILTER_GAMES_BY_GENRE';
export const FILTER_GAMES_BY_CREATOR = 'FILTER_GAMES_BY_CREATOR';
export const FILTER_GAMES_BY_RATING = 'FILTER_GAMES_BY_RATING';
export const FILTER_GAMES_BY_ALPHABET = 'FILTER_GAMES_BY_ALPHABET';